export const COMMIT_LOGIN = 'login'
export const COMMIT_SIGNIN = 'signin'
export const COMMIT_LOGINOUT = 'loginOut'
export const COMMIT_CITY = 'getCity'
export const COMMIT_ORDER = 'getOrder'
export const COMMIT_COMMENTS = 'getShopComments'
